#pragma once


enum class APPLICATION_VIEW_CHANGE
{
    AVC_ADDED,
    AVC_REMOVED,
    AVC_FORGOTTEN,
    AVC_VISIBLE,
    AVC_HIDDEN,
    AVC_AUMID,
    AVC_NEEDINESS,
    AVC_FOCUS,
    AVC_PENDING_FOCUS,
    AVC_UNFOCUS,
    AVC_SHOW_IN_SWITCHERS,
    AVC_REMOVED_FROM_SWITCHERS,
    AVC_THUMBNAIL_WINDOW,
    AVC_MONITOR_CHANGED,
    AVC_WINDOW_CHANGED,
    AVC_SIZE_CONSTRAINTS,
    AVC_TRAY_CHANGED,
    AVC_OWNER_CHANGED,
    AVC_ENTERPRISEID_CHANGED,
    AVC_ENTERPRISE_CHROME_PREFERENCE_CHANGED,
    AVC_CANTAB,
};

class ApplicationViewManager
{
};

